# Generated by Django 2.1.5 on 2019-04-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='inst',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Institute'),
            preserve_default=False,
        ),
    ]
