# Generated by Django 2.1.5 on 2019-04-22 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190422_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='crs_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrolledcourse',
            name='std_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Student'),
            preserve_default=False,
        ),
    ]
