# Generated by Django 2.1.5 on 2019-04-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190422_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crs_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='inst',
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='tchr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Teacher'),
        ),
    ]
