# Generated by Django 2.1.5 on 2019-04-22 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190422_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='AttendSheet_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.AttendanceSheet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='std_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='crs_tchr_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.CourseTeacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='endTime',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='lateTime',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='startTime',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
